/*
 * NOTE: put sounds in ABC order below.
 */
export const sounds: { [key: string]: any } = {
  "ba1": require("./ba1.mp3"),
  "bao1": require("./bao1.mp3"),
  "bi3": require("./bi3.mp3"),
  "bing1": require("./bing1.mp3"),
  "bu3": require("./bu3.mp3"),
  "che4": require("./che4.mp3"),
  "cun4": require("./cun4.mp3"),
  "da4": require("./da4.mp3"),
  "dao1": require("./dao1.mp3"),
  "er2": require("./er2.mp3"),
  "er4": require("./er4.mp3"),
  "fang1": require("./fang1.mp3"),
  "gun3": require("./gun3.mp3"),
  "han3": require("./han3.mp3"),
  "ji1": require("./ji1.mp3"),
  "jie2": require("./jie2.mp3"),
  "jiong3": require("./jiong3.mp3"),
  "jue2": require("./jue2.mp3"),
  "kan3": require("./kan3.mp3"),
  "kou3": require("./kou3.mp3"),
  "li4": require("./li4.mp3"),
  "mi4": require("./mi4.mp3"),
  "mian2": require("./mian2.mp3"),
  "nu3": require("./nu3.mp3"),
  "pie3": require("./pie3.mp3"),
  "ren2": require("./ren2.mp3"),
  "ru4": require("./ru4.mp3"),
  "shi1": require("./shi1.mp3"),
  "shi2": require("./shi2.mp3"),
  "shi4": require("./shi4.mp3"),
  "si1": require("./si1.mp3"),
  "sui1": require("./sui1.mp3"),
  "tou2": require("./tou2.mp3"),
  "tu3": require("./tu3.mp3"),
  "wang1": require("./wang1.mp3"),
  "wei2": require("./wei2.mp3"),
  "xi1": require("./xi1.mp3"),
  "xi4": require("./xi4.mp3"),
  "xiao3": require("./xiao3.mp3"),
  "yi1": require("./yi1.mp3"),
  "yi3": require("./yi3.mp3"),
  "you4": require("./you4.mp3"),
  "zhi3": require("./zhi3.mp3"),
  "zhu3": require("./zhu3.mp3"),
  "zi3": require("./zi3.mp3"),
};
